### ISSUE TITLE
Failed to scrape socket: malformed MIME header line: Primary script unknown

### ISSUE THREAD

**Issue by Lusitaniae** [kumina/phpfpm_exporter#1]
Hello,

While running the exporter I found this error coming up:
`2017/09/08 14:12:55 Failed to scrape socket: malformed MIME header line: Primary script unknown`
Which result in all metrics specific to phpfpm not being printed.

After some analysis I managed to fix by replacing the default value for scriptName from 

`/server-status-fpm.php`

to

`/status`

I'm using ubuntu 16.04 with the typical lemp stack.

**Comment by EdSchouten** [comment]
Fixed in pull request #2.
