### ISSUE TITLE
Failed to scrape socket: Failed to parse File not found. 

### ISSUE THREAD

**Issue by MichaelLee03351** [kumina/phpfpm_exporter#26]
Hi, 
I have download phpfpm_exporter and installed on some of my  web server on AWS EC2 with Bitnami/NGINX package.

Here is my phpfpm_exporter.service

> [Unit]
> Description = PHP-FPM Prometheus Exporter
> 
> [Service]
> SyslogIdentifier = phpfpm_exporter
> 
> ExecStart =/usr/local/bin/phpfpm_exporter --phpfpm.socket-paths /opt/bitnami/php/var/run/www.sock
> 
> [Install]
> WantedBy = multi-user.target

For some odd reason, one of the servers works perfectly fine, but then I am encourting this following error with others.

> Oct 27 08:02:52 ip-10-129-19-93 systemd[1]: Started PHP-FPM Prometheus Exporter.
> Oct 27 08:02:52 ip-10-129-19-93 phpfpm_exporter[18333]: 2022/10/27 08:02:52 Starting phpfpm_exporter (version=0.6.0, branch=HEAD, revision=7177e606317822df06d567a4c14d085c40d54ef6)
> Oct 27 08:02:52 ip-10-129-19-93 phpfpm_exporter[18333]: 2022/10/27 08:02:52 Build context (go=go1.16.5, user=root@742eee, date=20210605-16:49:46)
> Oct 27 08:02:52 ip-10-129-19-93 phpfpm_exporter[18333]: 2022/10/27 08:02:52 Starting Server: :9253
> Oct 27 08:03:05 ip-10-129-19-93 phpfpm_exporter[18333]: 2022/10/27 08:03:05 Failed to scrape socket: Failed to parse File not found.
> Oct 27 08:03:35 ip-10-129-19-93 phpfpm_exporter[18333]: 2022/10/27 08:03:35 Failed to scrape socket: Failed to parse File not found.
> Oct 27 08:04:05 ip-10-129-19-93 phpfpm_exporter[18333]: 2022/10/27 08:04:05 Failed to scrape socket: Failed to parse File not found.

Am I missing something? Can't figure out what's causing this.

**Comment by Lusitaniae** [comment]
does this exist?

/opt/bitnami/php/var/run/www.sock


Do you have `pm.status_path = /status` enabled on php fpm config? (its commented by default)

**Comment by MichaelLee03351** [comment]
@Lusitaniae 
this is what's in the php-fpm.conf
listen=/opt/bitnami/php/var/run/www.sock

I missed pm.status_path= /status , but after I have this enabled. Now I got this. 
Oct 27 12:51:01 ip-10-129-19-92 phpfpm_exporter[4517]: 2022/10/27 12:51:01 Failed to scrape socket: dial unix /opt/bitnami/php/var/run/www.sock: connect: no such file or directory

So I guss the www.sock file location isn't what I think it is.... 

I tried this 

> sudo grep -ri "sock;" /home/bitnami/stack/nginx/* | grep -v "#" |awk '{print $2,$3,$4}' | sed 's/fastcgi_pass unix://g' | sed 's/;//g' | sort -u

> /opt/bitnami/php/var/run/www.sock
and that URL is what it returns to me.

**Comment by MichaelLee03351** [comment]
@Lusitaniae 
Never mind~ I got it to work!

Thank you! This is a very useful tool! Keep up the great work!

**Comment by Lusitaniae** [comment]
no problem!
