### ISSUE TITLE
Monitor port based FPM pools

### ISSUE THREAD

**Issue by gnasistemes** [kumina/phpfpm_exporter#27]
Hello,

Just wanted to know if there's a way to monitor port based network based pools (EX: 127.0.0.1:9044) or endpoints as http://127.0.0.1/fpmpool

As far as I can see, I can only monitor sockets.

Thanks in advance.

**Comment by Lusitaniae** [comment]
This exporter only supports socket scraping 

I believe the alternative PHP exporter exports support http requests and should be able to accommodate your needs

**Comment by gnasistemes** [comment]
Thanks for the feedback @Lusitaniae
