### ISSUE TITLE
License is missing information

### ISSUE THREAD

**Issue by Lusitaniae** [kumina/phpfpm_exporter#4]
https://github.com/kumina/phpfpm_exporter/blob/514c36ba2e322e4595a8ad754f78791bff435560/LICENSE#L189

**Comment by EdSchouten** [comment]
That doesn't need to be filled in, right? That's merely an appendix of the license explaining how license information can be added to source files. That's also what it looks like in the Prometheus repo:

https://github.com/prometheus/prometheus/blob/master/LICENSE#L189

**Comment by Lusitaniae** [comment]
Indeed. I skim through the file quickly and didn't pay enough attention.
